[[preface]]
== Preface

Lettuce is a scalable thread-safe Redis client providing <<basic-usage,synchronous>, <<asynchronous-api,asynchronous>> and <<reactive-api,reactive>> APIs. Multiple threads may share one connection if they avoid blocking and transactional operations such as BLPOP and MULTI/EXEC. Multiple connections are efficiently managed by the excellent netty NIO framework. Support for advanced Redis features such as Sentinel, Cluster, and Redis data models is included.

This document is the reference guide for lettuce. It explains how to use lettuce, its concepts and semantics and the syntax.

You can read this reference guide in a linear fashion, or you can skip sections if something does not interest you.

This section provides some basic introduction to Redis. The rest of the document refers only to lettuce features and assumes the user is familiar with Redis concepts.

[[preface.redis]]
=== Knowing Redis
NoSQL stores have taken the storage world by storm. It is a vast domain with a plethora of solutions, terms and patterns (to make things worse even the term itself has multiple http://www.google.com/search?q=nosoql+acronym[meanings]). While some of the principles are common, it is crucial that the user is familiar to some degree with Redis. The best way to get acquainted to this solutions is to read their documentation and follow their documentation - it usually doesn't take more then 5-10 minutes to go through them and if you are coming from an RDMBS-only background many times these exercises can be an eye opener.

The jumping off ground for learning about Redis is http://www.redis.io/[redis.io]. Here is a list of other useful resources:

* The http://try.redis.io/[interactive tutorial] introduces Redis.
* The http://redis.io/commands[command references] explains Redis commands and contains links to getting started guides, reference documentation and tutorials.
* Redis https://redis.io/clients[Clients]

[[preface.requirements]]
=== Requirements

lettuce 4.x and 5.x binaries requires JDK level 8.0 and above.

In terms of http://redis.io/[Redis], at least 2.6.

=== Additional Help Resources

Learning a new framework is not always straight forward. In this section, we try to provide what we think is an easy to follow guide for starting with lettuce. However, if you encounter issues or you are just looking for an advice, feel free to use one of the links below:

[[preface.support]]
==== Support

There are a few support options available:

 * Lettuce on Stackoverflow http://stackoverflow.com/questions/tagged/lettuce[Stackoverflow] is a tag for all lettuce users to share information and help each other. Note that registration is needed *only* for posting.
 * Get in touch with the community on https://gitter.im/mp911de/lettuce[Gitter].
 * Google Group: https://groups.google.com/d/forum/lettuce-redis-client-users[lettuce-redis-client-users] or mailto:lettuce-redis-client-users@googlegroups.com
 * Report bugs (or ask questions) in Github issues https://github.com/mp911de/lettuce/issues

[[preface.development]]
==== Following Development

For information on the lettuce source code repository, nightly builds and snapshot artifacts please see the https://redis.paluch.biz[lettuce homepage]. You can help make lettuce best serve the needs of the lettuce community by interacting with developers through the Community on http://stackoverflow.com/questions/tagged/lettuce[Stackoverflow]. To follow developer activity look for the mailing list information on the https://redis.paluch.biz[lettuce homepage]. If you encounter a bug or want to suggest an improvement, please create a ticket on the lettuce issue https://github.com/mp911de/lettuce/issues[tracker].

=== Where to go from here
 * Head to <<getting-started>> if you feel like jumping straight into the code.
 * Go to <<ha-sharding>> for Master/Slave, Redis Sentinel and Redis Cluster topics.
 * In order to dig deeper into the core features of Reactor:
 ** If you’re looking for client configuration options, performance related behavior and how to use various transports, go to <<advanced-usage>>.
 ** See <<integration-extension>> for extending lettuce with codecs or integrate it in your CDI/Spring application.
 ** You want to know more about *at-least-once* and *at-most-once*? Take a look into <<command-execution-reliability>>.

